#goal definition
string operationMode # SETUP | SETUP_WITHOUT_CACHING | PERCEPTION | SAVE_FILTERED_POINTCLOUD
string objectModel
string tfNameForSortingClusters
int32 clusterIndex
geometry_msgs/Vector3 pcaCustomXFlipAxis
string filteredPointcloudSaveFrameId
---
#result definition
geometry_msgs/Pose pose
int32 percentage
string skillStatus
---
#feedback
int32 percentage
string skillStatus